<?php
$this->headTitle('Add User');

$this->mainMenu()->setActiveItemId('admin/users');

$this->pageBreadcrumbs()
     ->setItems([
        'Home'=>$this->url('home'),
        'Manage Users'=>$this->url('admin/users'),
        'Add User'=>$this->url('admin/users', ['action'=>'add'])
     ]);

$form->get('email')
     ->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'name@example.com'
     ]);

$form->get('full_name')
     ->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'John Doe'
     ]);

$form->get('status')
     ->setAttributes(['class'=>'form-control']);

$form->get('password')
     ->setAttributes(['class'=>'form-control']);

$form->get('confirm_password')
     ->setAttributes(['class'=>'form-control']);

$form->get('submit')
     ->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>

<h1>Add User</h1>

<p>Please fill out the following form and click the <i>Create</i> button.</p>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('email')); ?>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('full_name')); ?>
            <?php echo $this->formElement($form->get('full_name')); ?>
            <?php echo $this->formElementErrors($form->get('full_name')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('password')); ?>
            <?php echo $this->formElement($form->get('password')); ?>
            <?php echo $this->formElementErrors($form->get('password')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('confirm_password')); ?>
            <?php echo $this->formElement($form->get('confirm_password')); ?>
            <?php echo $this->formElementErrors($form->get('confirm_password')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('status')); ?>
            <?php echo $this->formElement($form->get('status')); ?>
            <?php echo $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
        <?php echo $this->formElement($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>    
</div>   