<?php
$this->headTitle('Change Password');

$this->mainMenu()->setActiveItemId('admin/users');

$this->pageBreadcrumbs()
     ->setItems([
        'Home'=>$this->url('home'),
        'Manage Users'=>$this->url('admin/users'),
        'Change Password'=>$this->url('admin/users', ['action'=>'set-password', 'id'=>$user->getId()])
     ]);

$form->get('old_password')
     ->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Enter old password'
     ]);

$form->get('new_password')
     ->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Enter new password'
     ]);

$form->get('confirm_new_password')
     ->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Re-enter new password'
     ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>

<h1>Change Password for <?php echo $this->escapeHtml($user->getEmail()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form); ?>
        
            <div class="form-group">
                <?php echo $this->formLabel($form->get('old_password')); ?>
                <?php echo $this->formElement($form->get('old_password')); ?>
                <?php echo $this->formElementErrors($form->get('old_password')); ?>                  
            </div>

            <div class="form-group">
                <?php echo $this->formLabel($form->get('new_password')); ?>
                <?php echo $this->formElement($form->get('new_password')); ?>
                <?php echo $this->formElementErrors($form->get('new_password')); ?>                  
            </div>

            <div class="form-group">
                <?php echo $this->formLabel($form->get('confirm_new_password')); ?>
                <?php echo $this->formElement($form->get('confirm_new_password')); ?>
                <?php echo $this->formElementErrors($form->get('confirm_new_password')); ?>                  
            </div>

            <?php echo $this->formElement($form->get('csrf')); ?>
            <?php echo $this->formElement($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>    
</div>