<?php
$this->headTitle('Edit User');

$this->mainMenu()->setActiveItemId('admin/users');

$this->pageBreadcrumbs()
     ->setItems([
        'Home'=>$this->url('home'),
        'Manage Users'=>$this->url('admin/users'),
        'Edit User'=>$this->url('admin/users', ['action'=>'edit', 'id'=>$user->getId()])
     ]);

$form->get('email')
     ->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'name@example.com'
     ]);

$form->get('full_name')
     ->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'John Doe'
     ]);

$form->get('status')
     ->setAttributes([
        'class'=>'form-control'
     ]);

$form->get('submit')
     ->setAttributes(['class'=>'btn btn-primary'])
     ->setValue('Save');

$form->prepare();
?>

<h1>Edit User <?php echo $this->escapeHtml($user->getEmail()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form); ?>
        
            <div class="form-group">
                <?php echo $this->formLabel($form->get('email')); ?>
                <?php echo $this->formElement($form->get('email')); ?>
                <?php echo $this->formElementErrors($form->get('email')); ?>                  
            </div>

            <div class="form-group">
                <?php echo $this->formLabel($form->get('full_name')); ?>
                <?php echo $this->formElement($form->get('full_name')); ?>
                <?php echo $this->formElementErrors($form->get('full_name')); ?>                  
            </div>

            <div class="form-group">
                <?php echo $this->formLabel($form->get('status')); ?>
                <?php echo $this->formElement($form->get('status')); ?>
                <?php echo $this->formElementErrors($form->get('status')); ?>                  
            </div>

            <?php echo $this->formElement($form->get('submit')); ?>
        
        <?php echo $this->form()->closeTag(); ?>
    </div>    
</div>