<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('admin/users');

$this->pageBreadcrumbs()
     ->setItems([
        'Home'=>$this->url('home'),
        'Manage Users'=>$this->url('admin/users'),
     ]);
?>

<h1>Manage Users</h1>

<p>
<a class="btn btn-default" href="
    <?php echo $this->url('admin/users', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New User
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>E-mail</th>
        <th>Full Name</th>
        <th>Date Created</th>
        <th>Status</th>        
        <th>Actions</th>        
    </tr>
    
    <?php foreach ($users as $user): ?>
    
        <tr>
            <td><?php echo $this->escapeHtml($user->getId()); ?></td>
            <td>
                <a href="<?php echo $this->url('admin/users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                    <?php echo $this->escapeHtml($user->getEmail()); ?>
                </a> 
            </td>
            <td><?php echo $this->escapeHtml($user->getFullName()); ?></a> 
            </td>
            <td><?php echo $this->escapeHtml($user->getDateCreated()); ?></td>        
            <td><?php echo $this->escapeHtml($user->getStatusAsString()); ?></td>
            <td>
                <a class="btn btn-info" href="<?php echo $this->url('admin/users', 
                        ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span> Edit
                </a>
                <a class="btn btn-default" href="<?php echo $this->url('admin/users',
                        ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                    <span class="glyphicon glyphicon-asterisk"></span> Change Password
                </a>
            </td>    
        </tr>
        
    <?php endforeach; ?>
</table>