<?php
$this->headTitle('Reset Password');

echo $this->flashMessenger()->render('error', ['alert', 'alert-warning']);
echo $this->flashMessenger()->render('success', ['alert', 'alert-success']);
echo $this->flashMessenger()->render('info', ['alert', 'alert-info']);

$form->get('email')
     ->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Email address'
     ]);

$form->get('submit')
     ->setAttributes([
        'class'=>'btn btn-large btn-primary'
     ]);

$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?php echo $this->form()->openTag($form); ?>

            <h2>Reset Password</h2>

            <p>Enter your e-mail address below to reset your password</p>

            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>                              

            <?php echo $this->formElement($form->get('captcha')); ?>
            <p class="hint">Enter the letters above as you see them.</p>

            <?php echo $this->formElement($form->get('submit')); ?>

            <?php echo $this->formElement($form->get('csrf')); ?>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>