<?php
$this->headTitle('View User');

$this->mainMenu()->setActiveItemId('admin/users');

$this->pageBreadcrumbs()
     ->setItems([
        'Home'=>$this->url('home'),
        'Manage Users'=>$this->url('admin/users'),
        'View User'=>$this->url('admin/users', ['action'=>'view', 'id'=>$user->getId()])
     ]);

echo $this->flashMessenger()->render('error', ['alert', 'alert-warning']);
echo $this->flashMessenger()->render('success', ['alert', 'alert-success']);
echo $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>View User</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?php echo $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?php echo $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th>Full Name:</th>
                <td><?php echo $this->escapeHtml($user->getFullName()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?php echo $this->escapeHtml($user->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?php echo $this->escapeHtml($user->getStatusAsString()) ?></th>
            </tr>
        </table>
    </div>
</div>