<?php echo $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php 
        echo $this->headTitle('Admin Demo')->setSeparator(' - ')->setAutoEscape(false);
        
        echo $this->headMeta()
                  ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                  ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        /* Le styles */
        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                   ->prependStylesheet($this->basePath('css/style.css'))
                   ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                   ->prependStylesheet($this->basePath('css/bootstrap.min.css'));
        
        /* Scripts */
        echo $this->headScript()
                  ->prependFile($this->basePath('js/bootstrap.min.js'))
                  ->prependFile($this->basePath('js/jquery-2.2.4.min.js')) ?>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <!-- Page header -->
                <div class="col-md-4">
                    <div class="app-caption">Admin Demo</div>
                </div>                
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Navigation bar -->
                    <?php
                    // Check if the activeMenuItemId passed to layout view model
                    // and if so, use it for setting active navbar item.
                    if (isset($activeMenuItemId)) {
                        $this->mainMenu()->setActiveItemId($activeMenuItemId);
                    }

                    // Render the navbar
                    echo $this->mainMenu()->render(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Breadcrumbs -->
                    <?php echo $this->pageBreadcrumbs()->render(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Page content placeholder -->
                    <?php echo $this->content; ?>
                </div>
            </div>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Your Company. All rights reserved.</p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>