<?php
$this->headTitle('Sign in');

$this->mainMenu()->setActiveItemId('login');

$form->get('email')
     ->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Email address',
        'required' => true,
        'autofocus' => true
     ])
     ->setLabelAttributes([
        'class' => 'sr-only'
     ]);

$form->get('password')
     ->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Password',
        'required' => true,
     ])
     ->setLabelAttributes([
        'class' => 'sr-only'
     ]); 
?>

<div class="row">
    <div class="col-md-offset-4 col-md-3">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">Please sign in</h2>
            <?php if ($isLoginError): ?>
                <div class="alert alert-warning" role="alert">
                    Incorrect login and/or password. 
                    <a href="<?php echo $this->url('admin/reset-password') ?>">Forgot password?</a>
                </div>
            <?php endif;
            echo $this->formLabel($form->get('email'));
            echo $this->formElement($form->get('email'));
            echo $this->formLabel($form->get('password'));
            echo $this->formElement($form->get('password')); ?>
            <div class="checkbox">
                <label>
                    <?php echo $this->formElement($form->get('remember_me')); ?> Remember me
                </label>
            </div>
            <?php 
            echo $this->formElement($form->get('redirect_url'));
            echo $this->formElement($form->get('csrf')) ?>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </form>
    </div>
</div>